### ISSUE TITLE
Pretty-print the json?

### ISSUE THREAD

**Issue by d33tah** [k0swe/dxcc-json#5]
Right now it's not convenient to view the json on GitHub. Could you pretty-print it so that it's easier to look things up in it straight from the website?

**Comment by xylo04** [comment]
I'd suggest getting familiar with the tool `jq` or similar JSON manipulation tools, they make it easy to filter, restructure and pretty print. Super useful!

But yes, I'll also change the checked-in file to be pretty-printed.
